---

- name: Ensure unzip is installed (required for AWS CLI)
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Download AWS CLI v2 installer
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0644'

- name: Unzip AWS CLI package
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Install AWS CLI
  command: "/tmp/aws/install --update"
  args:
    creates: /usr/local/bin/aws

- name: Verify AWS CLI installation
  command: aws --version
  register: aws_cli_version
  changed_when: false

- name: Display installed AWS CLI version
  debug:
    msg: "✅ AWS CLI successfully installed: {{ aws_cli_version.stdout }}"
