# roles/sonarqube/tasks/main.yml
- name: Pull latest SonarQube Docker image
  docker_image:
    name: sonarqube:community
    source: pull

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:community
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
    volumes:
      - /mnt/docker/sonarqube-data:/opt/sonarqube/data



