---
- name: Install Java (SonarQube requirement)
  apt:
    name: openjdk-11-jdk
    state: present

- name: Download SonarQube
  get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip
    dest: /opt/sonarqube.zip

- name: Unzip SonarQube
  unarchive:
    src: /opt/sonarqube.zip
    dest: /opt/
    remote_src: yes

- name: Start SonarQube (manual start for simplicity)
  shell: "/opt/sonarqube-9.9.0.65466/bin/linux-x86-64/sonar.sh start"
