---
# ==============================
# Kubernetes Master Setup (Ubuntu 20.04 / 22.04)
# ==============================

- name: Disable swap
  command: swapoff -a
  become: yes

- name: Remove swap entry from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*swap.*)$'
    replace: '# \1'
  become: yes

# ==============================
# Kernel Modules and Sysctl
# ==============================
- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  become: yes

- name: Load required kernel modules immediately
  command: modprobe {{ item }}
  loop:
    - overlay
    - br_netfilter
  become: yes

- name: Set sysctl params for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: yes

- name: Apply sysctl changes
  command: sysctl --system
  become: yes

# ==============================
# Install Kubernetes Packages (v1.30+ repo)
# ==============================
- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: yes
  become: yes

- name: Add Kubernetes APT key (v1.30 repo)
  ansible.builtin.shell: |
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    executable: /bin/bash
  become: yes

- name: Add Kubernetes APT repository
  ansible.builtin.shell: |
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash
  become: yes

- name: Update APT cache
  apt:
    update_cache: yes
  become: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  become: yes

- name: Hold Kubernetes packages
  command: apt-mark hold kubelet kubeadm kubectl
  become: yes

# ==============================
# Initialize Kubernetes Master
# ==============================
- name: Initialize Kubernetes master node
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: "'k8s_master' in group_names"
  become: yes

- name: Setup kubeconfig for ubuntu user
  shell: |
    mkdir -p /home/ubuntu/.kube
    cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    chown ubuntu:ubuntu /home/ubuntu/.kube/config
  args:
    executable: /bin/bash
  when: "'k8s_master' in group_names"
  become: yes

- name: Install Flannel CNI
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  when: "'k8s_master' in group_names"
  become: yes



