---
- name: Disable swap
  command: swapoff -a
  become: yes

- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
      
- name: Set sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  notify:
    - Apply sysctl

- name: Install Kubernetes packages
  apt:
    name: [kubelet, kubeadm, kubectl]
    state: present
    update_cache: yes

- name: Hold kube packages
  apt:
    name: [kubelet, kubeadm, kubectl]
    state: hold

- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: "'kubernetes-master' in group_names"

- name: Setup kubeconfig
  command: >
    mkdir -p /home/ubuntu/.kube &&
    cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config &&
    chown ubuntu:ubuntu /home/ubuntu/.kube/config
  when: "'kubernetes-master' in group_names"

- name: Install Flannel CNI
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  when: "'kubernetes-master' in group_names"
