---
- name: Install dependencies for Jenkins
  apt:
    name:
      - openjdk-17-jdk
      - wget
      - curl
    state: present
    update_cache: yes

- name: Add Jenkins GPG key
  command: wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
  args:
    creates: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins repository
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" \
    | tee /etc/apt/sources.list.d/jenkins.list > /dev/null

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Enable and start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins service to start
  wait_for:
    port: 8080
    timeout: 60

- name: Get Jenkins initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password
  changed_when: false

- name: Print Jenkins access info
  debug:
    msg: |
      Jenkins Installed Successfully 🎉
      URL: http://{{ ansible_host }}:8080
      Username: admin
      Initial Password: {{ jenkins_password.stdout }}

