---
- name: Setup all tools
  hosts: all
  become: yes
  roles:
    - docker

- name: Setup Jenkins Server
  hosts: jenkins
  become: yes
  roles:
    - jenkins
    - sonarqube
    - nexus
    - trivy
    - aws-cli

- name: Setup Kubernetes Master Node
  hosts: k8s_master
  become: yes
  roles:
    - kubernetes
    - prometheus
    - grafana

- name: Setup Kubernetes Worker Nodes
  hosts: k8s_worker
  become: yes
  roles:
    - worker
